---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: odoo-education
  namespace: odoo-stg
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: odoo-education
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
